apiVersion: v1
kind: Pod
metadata:
  name: nats
  labels:
    app: nats
    version: v1
spec:
  containers:
    - name: nats-standalone
      image: nats
      ports:
        - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  ports:
    - port: 4222
  selector:
    app: nats
    version: v1
