apiVersion: v1
kind: Secret
metadata:
  name: connection-secrets
  namespace: capturetweet
type: Opague
stringData:
  MONGO_SERVER_URL: "mongodb://***REMOVED***:***REMOVED***@mongodb:27017"
  TWITTER_ACCESS_SECRET: "***REMOVED***"
  TWITTER_ACCESS_TOKEN: "***REMOVED***"
  TWITTER_CONSUMER_KEY: "***REMOVED***"
  TWITTER_CONSUMER_SECRET: "***REMOVED***"
  GRAPHQL_ENABLE_PLAYGROUND: "false"
  ALGOLIA_SECRET: "***REMOVED***"
  ALGOLIA_CLIENT_ID: "***REMOVED***"
  ALGOLIA_INDEX: "tweets-K8S"
  DOCSTORE_TWEETS: "mongo://capturetweet/tweets?id_field=id"
  DOCSTORE_USERS: "mongo://capturetweet/authors?id_field=id"
  DOCSTORE_CONTACT_US: "mongo://capturetweet/contactUs?id_field=id"
  TOPIC_CAPTURE: "nats://capture.request"
  NATS_SERVER_URL: "nats://nats-svc:4222"
  SENDGRID_TEMPLATE_ID: "***REMOVED***"
  SENDGRID_APIKEY: "***REMOVED***"
