version: '3'

services:

  nats:
    image: nats
    container_name: ct_pubsub
    ports:
      - "4222:4222"

  db:
    image: postgres:13
    container_name: cf_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
