version: '3'

services:
  postgres:
    image: postgres:12
    container_name: ct_pdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - capture_pdb:/var/lib/postgresql/data

volumes:
  capture_pdb: {}
