version: '3'

services:
  mongo:
    image: mongo
    container_name: ct_mdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - capture_mdb_data:/data/db

  nats:
    image: nats
    container_name: ct_pubsub
    ports:
      - "4222:4222"

volumes:
  capture_mdb_data: {}
