steps:
  - name: 'golang:1.14'
    args: ['go', 'build', '-a', '-installsuffix','cgo', '-o' ,'tmp/app','.']
    env: ['GO111MODULE=on','CGO_ENABLED=0','GOOS=linux']
    dir: 'cmd/thumb'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/beta-thumb:$SHORT_SHA', '.']
    dir: 'cmd/thumb'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/beta-thumb:$SHORT_SHA']
    dir: 'cmd/thumb'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run','deploy','beta-thumb','--image','eu.gcr.io/$PROJECT_ID/beta-thumb:$SHORT_SHA', '--platform', 'managed','--region','europe-west1']
