// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"capturetweet.com/internal/ent/contactus"
	"capturetweet.com/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContactUsQuery is the builder for querying ContactUs entities.
type ContactUsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ContactUs
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContactUsQuery builder.
func (cuq *ContactUsQuery) Where(ps ...predicate.ContactUs) *ContactUsQuery {
	cuq.predicates = append(cuq.predicates, ps...)
	return cuq
}

// Limit adds a limit step to the query.
func (cuq *ContactUsQuery) Limit(limit int) *ContactUsQuery {
	cuq.limit = &limit
	return cuq
}

// Offset adds an offset step to the query.
func (cuq *ContactUsQuery) Offset(offset int) *ContactUsQuery {
	cuq.offset = &offset
	return cuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cuq *ContactUsQuery) Unique(unique bool) *ContactUsQuery {
	cuq.unique = &unique
	return cuq
}

// Order adds an order step to the query.
func (cuq *ContactUsQuery) Order(o ...OrderFunc) *ContactUsQuery {
	cuq.order = append(cuq.order, o...)
	return cuq
}

// First returns the first ContactUs entity from the query.
// Returns a *NotFoundError when no ContactUs was found.
func (cuq *ContactUsQuery) First(ctx context.Context) (*ContactUs, error) {
	nodes, err := cuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contactus.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cuq *ContactUsQuery) FirstX(ctx context.Context) *ContactUs {
	node, err := cuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContactUs ID from the query.
// Returns a *NotFoundError when no ContactUs ID was found.
func (cuq *ContactUsQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contactus.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cuq *ContactUsQuery) FirstIDX(ctx context.Context) string {
	id, err := cuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContactUs entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ContactUs entity is not found.
// Returns a *NotFoundError when no ContactUs entities are found.
func (cuq *ContactUsQuery) Only(ctx context.Context) (*ContactUs, error) {
	nodes, err := cuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contactus.Label}
	default:
		return nil, &NotSingularError{contactus.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cuq *ContactUsQuery) OnlyX(ctx context.Context) *ContactUs {
	node, err := cuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContactUs ID in the query.
// Returns a *NotSingularError when exactly one ContactUs ID is not found.
// Returns a *NotFoundError when no entities are found.
func (cuq *ContactUsQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = cuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = &NotSingularError{contactus.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cuq *ContactUsQuery) OnlyIDX(ctx context.Context) string {
	id, err := cuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContactUsSlice.
func (cuq *ContactUsQuery) All(ctx context.Context) ([]*ContactUs, error) {
	if err := cuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cuq *ContactUsQuery) AllX(ctx context.Context) []*ContactUs {
	nodes, err := cuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContactUs IDs.
func (cuq *ContactUsQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := cuq.Select(contactus.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cuq *ContactUsQuery) IDsX(ctx context.Context) []string {
	ids, err := cuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cuq *ContactUsQuery) Count(ctx context.Context) (int, error) {
	if err := cuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cuq *ContactUsQuery) CountX(ctx context.Context) int {
	count, err := cuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cuq *ContactUsQuery) Exist(ctx context.Context) (bool, error) {
	if err := cuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cuq *ContactUsQuery) ExistX(ctx context.Context) bool {
	exist, err := cuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContactUsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cuq *ContactUsQuery) Clone() *ContactUsQuery {
	if cuq == nil {
		return nil
	}
	return &ContactUsQuery{
		config:     cuq.config,
		limit:      cuq.limit,
		offset:     cuq.offset,
		order:      append([]OrderFunc{}, cuq.order...),
		predicates: append([]predicate.ContactUs{}, cuq.predicates...),
		// clone intermediate query.
		sql:  cuq.sql.Clone(),
		path: cuq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContactUs.Query().
//		GroupBy(contactus.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cuq *ContactUsQuery) GroupBy(field string, fields ...string) *ContactUsGroupBy {
	group := &ContactUsGroupBy{config: cuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ContactUs.Query().
//		Select(contactus.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (cuq *ContactUsQuery) Select(fields ...string) *ContactUsSelect {
	cuq.fields = append(cuq.fields, fields...)
	return &ContactUsSelect{ContactUsQuery: cuq}
}

func (cuq *ContactUsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cuq.fields {
		if !contactus.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cuq.path != nil {
		prev, err := cuq.path(ctx)
		if err != nil {
			return err
		}
		cuq.sql = prev
	}
	return nil
}

func (cuq *ContactUsQuery) sqlAll(ctx context.Context) ([]*ContactUs, error) {
	var (
		nodes = []*ContactUs{}
		_spec = cuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ContactUs{config: cuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, cuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cuq *ContactUsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cuq.querySpec()
	_spec.Node.Columns = cuq.fields
	if len(cuq.fields) > 0 {
		_spec.Unique = cuq.unique != nil && *cuq.unique
	}
	return sqlgraph.CountNodes(ctx, cuq.driver, _spec)
}

func (cuq *ContactUsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cuq *ContactUsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   contactus.Table,
			Columns: contactus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: contactus.FieldID,
			},
		},
		From:   cuq.sql,
		Unique: true,
	}
	if unique := cuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contactus.FieldID)
		for i := range fields {
			if fields[i] != contactus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cuq *ContactUsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cuq.driver.Dialect())
	t1 := builder.Table(contactus.Table)
	columns := cuq.fields
	if len(columns) == 0 {
		columns = contactus.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cuq.sql != nil {
		selector = cuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cuq.unique != nil && *cuq.unique {
		selector.Distinct()
	}
	for _, p := range cuq.predicates {
		p(selector)
	}
	for _, p := range cuq.order {
		p(selector)
	}
	if offset := cuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContactUsGroupBy is the group-by builder for ContactUs entities.
type ContactUsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cugb *ContactUsGroupBy) Aggregate(fns ...AggregateFunc) *ContactUsGroupBy {
	cugb.fns = append(cugb.fns, fns...)
	return cugb
}

// Scan applies the group-by query and scans the result into the given value.
func (cugb *ContactUsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cugb.path(ctx)
	if err != nil {
		return err
	}
	cugb.sql = query
	return cugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cugb *ContactUsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := cugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: ContactUsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cugb *ContactUsGroupBy) StringsX(ctx context.Context) []string {
	v, err := cugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cugb *ContactUsGroupBy) StringX(ctx context.Context) string {
	v, err := cugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: ContactUsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cugb *ContactUsGroupBy) IntsX(ctx context.Context) []int {
	v, err := cugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cugb *ContactUsGroupBy) IntX(ctx context.Context) int {
	v, err := cugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: ContactUsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cugb *ContactUsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := cugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cugb *ContactUsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := cugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(cugb.fields) > 1 {
		return nil, errors.New("ent: ContactUsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := cugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cugb *ContactUsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := cugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cugb *ContactUsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cugb *ContactUsGroupBy) BoolX(ctx context.Context) bool {
	v, err := cugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cugb *ContactUsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cugb.fields {
		if !contactus.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cugb *ContactUsGroupBy) sqlQuery() *sql.Selector {
	selector := cugb.sql.Select()
	aggregation := make([]string, 0, len(cugb.fns))
	for _, fn := range cugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cugb.fields)+len(cugb.fns))
		for _, f := range cugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cugb.fields...)...)
}

// ContactUsSelect is the builder for selecting fields of ContactUs entities.
type ContactUsSelect struct {
	*ContactUsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cus *ContactUsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cus.prepareQuery(ctx); err != nil {
		return err
	}
	cus.sql = cus.ContactUsQuery.sqlQuery(ctx)
	return cus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cus *ContactUsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: ContactUsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cus *ContactUsSelect) StringsX(ctx context.Context) []string {
	v, err := cus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cus *ContactUsSelect) StringX(ctx context.Context) string {
	v, err := cus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: ContactUsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cus *ContactUsSelect) IntsX(ctx context.Context) []int {
	v, err := cus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cus *ContactUsSelect) IntX(ctx context.Context) int {
	v, err := cus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: ContactUsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cus *ContactUsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cus *ContactUsSelect) Float64X(ctx context.Context) float64 {
	v, err := cus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cus.fields) > 1 {
		return nil, errors.New("ent: ContactUsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cus *ContactUsSelect) BoolsX(ctx context.Context) []bool {
	v, err := cus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cus *ContactUsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{contactus.Label}
	default:
		err = fmt.Errorf("ent: ContactUsSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cus *ContactUsSelect) BoolX(ctx context.Context) bool {
	v, err := cus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cus *ContactUsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cus.sql.Query()
	if err := cus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
