// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"capturetweet.com/internal/ent/contactus"
	"capturetweet.com/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContactUsDelete is the builder for deleting a ContactUs entity.
type ContactUsDelete struct {
	config
	hooks    []Hook
	mutation *ContactUsMutation
}

// Where appends a list predicates to the ContactUsDelete builder.
func (cud *ContactUsDelete) Where(ps ...predicate.ContactUs) *ContactUsDelete {
	cud.mutation.Where(ps...)
	return cud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cud *ContactUsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cud.hooks) == 0 {
		affected, err = cud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ContactUsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cud.mutation = mutation
			affected, err = cud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cud.hooks) - 1; i >= 0; i-- {
			if cud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cud *ContactUsDelete) ExecX(ctx context.Context) int {
	n, err := cud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cud *ContactUsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: contactus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: contactus.FieldID,
			},
		},
	}
	if ps := cud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ContactUsDeleteOne is the builder for deleting a single ContactUs entity.
type ContactUsDeleteOne struct {
	cud *ContactUsDelete
}

// Exec executes the deletion query.
func (cudo *ContactUsDeleteOne) Exec(ctx context.Context) error {
	n, err := cudo.cud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contactus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cudo *ContactUsDeleteOne) ExecX(ctx context.Context) {
	cudo.cud.ExecX(ctx)
}
