// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"capturetweet.com/internal/ent/schema"
	"capturetweet.com/internal/ent/tweet"
	"capturetweet.com/internal/ent/user"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TweetCreate is the builder for creating a Tweet entity.
type TweetCreate struct {
	config
	mutation *TweetMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tc *TweetCreate) SetCreatedAt(t time.Time) *TweetCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TweetCreate) SetNillableCreatedAt(t *time.Time) *TweetCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TweetCreate) SetUpdatedAt(t time.Time) *TweetCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TweetCreate) SetNillableUpdatedAt(t *time.Time) *TweetCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetFullText sets the "full_text" field.
func (tc *TweetCreate) SetFullText(s string) *TweetCreate {
	tc.mutation.SetFullText(s)
	return tc
}

// SetCaptureURL sets the "capture_url" field.
func (tc *TweetCreate) SetCaptureURL(s string) *TweetCreate {
	tc.mutation.SetCaptureURL(s)
	return tc
}

// SetNillableCaptureURL sets the "capture_url" field if the given value is not nil.
func (tc *TweetCreate) SetNillableCaptureURL(s *string) *TweetCreate {
	if s != nil {
		tc.SetCaptureURL(*s)
	}
	return tc
}

// SetCaptureThumbURL sets the "capture_thumb_url" field.
func (tc *TweetCreate) SetCaptureThumbURL(s string) *TweetCreate {
	tc.mutation.SetCaptureThumbURL(s)
	return tc
}

// SetNillableCaptureThumbURL sets the "capture_thumb_url" field if the given value is not nil.
func (tc *TweetCreate) SetNillableCaptureThumbURL(s *string) *TweetCreate {
	if s != nil {
		tc.SetCaptureThumbURL(*s)
	}
	return tc
}

// SetLang sets the "lang" field.
func (tc *TweetCreate) SetLang(s string) *TweetCreate {
	tc.mutation.SetLang(s)
	return tc
}

// SetFavoriteCount sets the "favorite_count" field.
func (tc *TweetCreate) SetFavoriteCount(i int) *TweetCreate {
	tc.mutation.SetFavoriteCount(i)
	return tc
}

// SetNillableFavoriteCount sets the "favorite_count" field if the given value is not nil.
func (tc *TweetCreate) SetNillableFavoriteCount(i *int) *TweetCreate {
	if i != nil {
		tc.SetFavoriteCount(*i)
	}
	return tc
}

// SetRetweetCount sets the "retweet_count" field.
func (tc *TweetCreate) SetRetweetCount(i int) *TweetCreate {
	tc.mutation.SetRetweetCount(i)
	return tc
}

// SetNillableRetweetCount sets the "retweet_count" field if the given value is not nil.
func (tc *TweetCreate) SetNillableRetweetCount(i *int) *TweetCreate {
	if i != nil {
		tc.SetRetweetCount(*i)
	}
	return tc
}

// SetAuthorID sets the "author_id" field.
func (tc *TweetCreate) SetAuthorID(s string) *TweetCreate {
	tc.mutation.SetAuthorID(s)
	return tc
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (tc *TweetCreate) SetNillableAuthorID(s *string) *TweetCreate {
	if s != nil {
		tc.SetAuthorID(*s)
	}
	return tc
}

// SetResources sets the "resources" field.
func (tc *TweetCreate) SetResources(s []schema.Resource) *TweetCreate {
	tc.mutation.SetResources(s)
	return tc
}

// SetPostedAt sets the "posted_at" field.
func (tc *TweetCreate) SetPostedAt(t time.Time) *TweetCreate {
	tc.mutation.SetPostedAt(t)
	return tc
}

// SetID sets the "id" field.
func (tc *TweetCreate) SetID(s string) *TweetCreate {
	tc.mutation.SetID(s)
	return tc
}

// SetAuthor sets the "author" edge to the User entity.
func (tc *TweetCreate) SetAuthor(u *User) *TweetCreate {
	return tc.SetAuthorID(u.ID)
}

// Mutation returns the TweetMutation object of the builder.
func (tc *TweetCreate) Mutation() *TweetMutation {
	return tc.mutation
}

// Save creates the Tweet in the database.
func (tc *TweetCreate) Save(ctx context.Context) (*Tweet, error) {
	var (
		err  error
		node *Tweet
	)
	tc.defaults()
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TweetMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TweetCreate) SaveX(ctx context.Context) *Tweet {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TweetCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TweetCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TweetCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := tweet.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := tweet.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.FavoriteCount(); !ok {
		v := tweet.DefaultFavoriteCount
		tc.mutation.SetFavoriteCount(v)
	}
	if _, ok := tc.mutation.RetweetCount(); !ok {
		v := tweet.DefaultRetweetCount
		tc.mutation.SetRetweetCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TweetCreate) check() error {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tweet.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Tweet.updated_at"`)}
	}
	if _, ok := tc.mutation.FullText(); !ok {
		return &ValidationError{Name: "full_text", err: errors.New(`ent: missing required field "Tweet.full_text"`)}
	}
	if v, ok := tc.mutation.FullText(); ok {
		if err := tweet.FullTextValidator(v); err != nil {
			return &ValidationError{Name: "full_text", err: fmt.Errorf(`ent: validator failed for field "Tweet.full_text": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Lang(); !ok {
		return &ValidationError{Name: "lang", err: errors.New(`ent: missing required field "Tweet.lang"`)}
	}
	if v, ok := tc.mutation.Lang(); ok {
		if err := tweet.LangValidator(v); err != nil {
			return &ValidationError{Name: "lang", err: fmt.Errorf(`ent: validator failed for field "Tweet.lang": %w`, err)}
		}
	}
	if _, ok := tc.mutation.FavoriteCount(); !ok {
		return &ValidationError{Name: "favorite_count", err: errors.New(`ent: missing required field "Tweet.favorite_count"`)}
	}
	if _, ok := tc.mutation.RetweetCount(); !ok {
		return &ValidationError{Name: "retweet_count", err: errors.New(`ent: missing required field "Tweet.retweet_count"`)}
	}
	if v, ok := tc.mutation.AuthorID(); ok {
		if err := tweet.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "Tweet.author_id": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Resources(); !ok {
		return &ValidationError{Name: "resources", err: errors.New(`ent: missing required field "Tweet.resources"`)}
	}
	if _, ok := tc.mutation.PostedAt(); !ok {
		return &ValidationError{Name: "posted_at", err: errors.New(`ent: missing required field "Tweet.posted_at"`)}
	}
	if v, ok := tc.mutation.ID(); ok {
		if err := tweet.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Tweet.id": %w`, err)}
		}
	}
	return nil
}

func (tc *TweetCreate) sqlSave(ctx context.Context) (*Tweet, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Tweet.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (tc *TweetCreate) createSpec() (*Tweet, *sqlgraph.CreateSpec) {
	var (
		_node = &Tweet{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tweet.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: tweet.FieldID,
			},
		}
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tweet.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tweet.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.FullText(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tweet.FieldFullText,
		})
		_node.FullText = value
	}
	if value, ok := tc.mutation.CaptureURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tweet.FieldCaptureURL,
		})
		_node.CaptureURL = value
	}
	if value, ok := tc.mutation.CaptureThumbURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tweet.FieldCaptureThumbURL,
		})
		_node.CaptureThumbURL = value
	}
	if value, ok := tc.mutation.Lang(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tweet.FieldLang,
		})
		_node.Lang = value
	}
	if value, ok := tc.mutation.FavoriteCount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tweet.FieldFavoriteCount,
		})
		_node.FavoriteCount = value
	}
	if value, ok := tc.mutation.RetweetCount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tweet.FieldRetweetCount,
		})
		_node.RetweetCount = value
	}
	if value, ok := tc.mutation.Resources(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tweet.FieldResources,
		})
		_node.Resources = value
	}
	if value, ok := tc.mutation.PostedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tweet.FieldPostedAt,
		})
		_node.PostedAt = value
	}
	if nodes := tc.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tweet.AuthorTable,
			Columns: []string{tweet.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TweetCreateBulk is the builder for creating many Tweet entities in bulk.
type TweetCreateBulk struct {
	config
	builders []*TweetCreate
}

// Save creates the Tweet entities in the database.
func (tcb *TweetCreateBulk) Save(ctx context.Context) ([]*Tweet, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tweet, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TweetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TweetCreateBulk) SaveX(ctx context.Context) []*Tweet {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TweetCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TweetCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
