// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ContactUs is the predicate function for contactus builders.
type ContactUs func(*sql.Selector)

// Tweet is the predicate function for tweet builders.
type Tweet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
