// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"com.capturetweet/api"
	"com.capturetweet/internal/infra"
	"com.capturetweet/pkg/browser"
	"com.capturetweet/pkg/tweet"
)

// Injectors from wire.go:

func initializeBrowserService() api.BrowserService {
	collection := infra.NewTweetCollection()
	repository := tweet.NewRepository(collection)
	tweetService := tweet.NewServiceWithRepository(repository)
	bucket := infra.NewBucketFromEnvironment()
	browserService := browser.NewService(tweetService, bucket)
	return browserService
}
