// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"capturetweet.com/api"
	"capturetweet.com/internal/infra"
	"capturetweet.com/pkg/browser"
	"capturetweet.com/pkg/tweet"
)

// Injectors from wire.go:

func initializeBrowserService() api.BrowserService {
	client := infra.NewPostgresDatabase()
	repository := tweet.NewRepository(client)
	tweetService := tweet.NewServiceWithRepository(repository)
	bucket := infra.NewBucketFromEnvironment()
	browserService := browser.NewService(tweetService, bucket)
	return browserService
}
