// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"capturetweet.com/api"
	"capturetweet.com/internal/infra"
	"capturetweet.com/pkg/browser"
	"capturetweet.com/pkg/tweet"
)

// Injectors from wire.go:

func initializeBrowserService() api.BrowserService {
	collection := infra.NewTweetCollection()
	repository := tweet.NewRepository(collection)
	tweetService := tweet.NewServiceWithRepository(repository)
	bucket := infra.NewBucketFromEnvironment()
	browserService := browser.NewService(tweetService, bucket)
	return browserService
}
