steps:
  - name: 'node:lts'
    args: ['yarn']
    dir: 'web/app'

  - name: 'node:lts'
    args: ['yarn','test']
    dir: 'web/app'

  - name: 'node:lts'
    args: ['yarn', 'build:prod']
    dir: 'web/app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: ['gsutil', '-h','Cache-Control:public,max-age=86400','-m' ,'rsync','-R', 'build','gs://capturetweet.com']
    dir: 'web/app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: ['gsutil', '-h','Cache-Control:public,max-age=2592000','-m' ,'rsync','-R', 'build/static','gs://capturetweet.com/static']
    dir: 'web/app'
