steps:
  - name: 'golang:1.16'
    args: ['go', 'build', '-a', '-installsuffix','cgo','-ldflags','"-w -X main.version=$SHORT_SHA"', '-o' ,'tmp/app','.']
    env: ['GO111MODULE=on','CGO_ENABLED=0','GOOS=linux']
    dir: 'cmd/dlqcapture'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: ['docker','build', '-f', 'Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/dlqcapture:$SHORT_SHA', '.']
    dir: 'cmd/dlqcapture'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: ['docker', 'push', 'eu.gcr.io/$PROJECT_ID/dlqcapture:$SHORT_SHA']
    dir: 'cmd/dlqcapture'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: ['gcloud','run','deploy','dlq-capture','--image','eu.gcr.io/$PROJECT_ID/dlqcapture:$SHORT_SHA', '--platform', 'managed','--region','europe-west1']
