// Code generated by MockGen. DO NOT EDIT.
// Source: capturetweet.com/internal/infra (interfaces: IndexInterface)
//
// Generated by this command:
//
//	mockgen -package=infra -self_package=capturetweet.com/internal/infra -destination=algolia_mock.go . IndexInterface
//

// Package infra is a generated GoMock package.
package infra

import (
	reflect "reflect"

	search "github.com/algolia/algoliasearch-client-go/v3/algolia/search"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexInterface is a mock of IndexInterface interface.
type MockIndexInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIndexInterfaceMockRecorder
}

// MockIndexInterfaceMockRecorder is the mock recorder for MockIndexInterface.
type MockIndexInterfaceMockRecorder struct {
	mock *MockIndexInterface
}

// NewMockIndexInterface creates a new mock instance.
func NewMockIndexInterface(ctrl *gomock.Controller) *MockIndexInterface {
	mock := &MockIndexInterface{ctrl: ctrl}
	mock.recorder = &MockIndexInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexInterface) EXPECT() *MockIndexInterfaceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIndexInterface) Delete(arg0 ...any) (search.DeleteTaskRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(search.DeleteTaskRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIndexInterfaceMockRecorder) Delete(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIndexInterface)(nil).Delete), arg0...)
}

// GetObject mocks base method.
func (m *MockIndexInterface) GetObject(arg0 string, arg1 any, arg2 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetObject indicates an expected call of GetObject.
func (mr *MockIndexInterfaceMockRecorder) GetObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockIndexInterface)(nil).GetObject), varargs...)
}

// SaveObject mocks base method.
func (m *MockIndexInterface) SaveObject(arg0 any, arg1 ...any) (search.SaveObjectRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveObject", varargs...)
	ret0, _ := ret[0].(search.SaveObjectRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveObject indicates an expected call of SaveObject.
func (mr *MockIndexInterfaceMockRecorder) SaveObject(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveObject", reflect.TypeOf((*MockIndexInterface)(nil).SaveObject), varargs...)
}

// Search mocks base method.
func (m *MockIndexInterface) Search(arg0 string, arg1 ...any) (search.QueryRes, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(search.QueryRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIndexInterfaceMockRecorder) Search(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIndexInterface)(nil).Search), varargs...)
}
