// Code generated by MockGen. DO NOT EDIT.
// Source: capturetweet.com/api (interfaces: UserService,TweetService,SearchService,BrowserService,ContentService)
//
// Generated by this command:
//
//	mockgen -package=api -self_package=capturetweet.com/api -destination=service_mock.go . UserService,TweetService,SearchService,BrowserService,ContentService
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	anaconda "github.com/ChimeraCoder/anaconda"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockUserService) FindById(ctx context.Context, id string) (*UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockUserServiceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockUserService)(nil).FindById), ctx, id)
}

// FindOrCreate mocks base method.
func (m *MockUserService) FindOrCreate(ctx context.Context, user *anaconda.User) (*UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, user)
	ret0, _ := ret[0].(*UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockUserServiceMockRecorder) FindOrCreate(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockUserService)(nil).FindOrCreate), ctx, user)
}

// MockTweetService is a mock of TweetService interface.
type MockTweetService struct {
	ctrl     *gomock.Controller
	recorder *MockTweetServiceMockRecorder
	isgomock struct{}
}

// MockTweetServiceMockRecorder is the mock recorder for MockTweetService.
type MockTweetServiceMockRecorder struct {
	mock *MockTweetService
}

// NewMockTweetService creates a new mock instance.
func NewMockTweetService(ctrl *gomock.Controller) *MockTweetService {
	mock := &MockTweetService{ctrl: ctrl}
	mock.recorder = &MockTweetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTweetService) EXPECT() *MockTweetServiceMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockTweetService) FindById(ctx context.Context, id string) (*TweetModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(*TweetModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockTweetServiceMockRecorder) FindById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockTweetService)(nil).FindById), ctx, id)
}

// Search mocks base method.
func (m *MockTweetService) Search(ctx context.Context, term string, size, start, page int) ([]TweetModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, term, size, start, page)
	ret0, _ := ret[0].([]TweetModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockTweetServiceMockRecorder) Search(ctx, term, size, start, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockTweetService)(nil).Search), ctx, term, size, start, page)
}

// SearchByUser mocks base method.
func (m *MockTweetService) SearchByUser(ctx context.Context, userId string) ([]TweetModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByUser", ctx, userId)
	ret0, _ := ret[0].([]TweetModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByUser indicates an expected call of SearchByUser.
func (mr *MockTweetServiceMockRecorder) SearchByUser(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByUser", reflect.TypeOf((*MockTweetService)(nil).SearchByUser), ctx, userId)
}

// Store mocks base method.
func (m *MockTweetService) Store(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockTweetServiceMockRecorder) Store(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTweetService)(nil).Store), ctx, url)
}

// UpdateLargeImage mocks base method.
func (m *MockTweetService) UpdateLargeImage(ctx context.Context, id, captureUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLargeImage", ctx, id, captureUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLargeImage indicates an expected call of UpdateLargeImage.
func (mr *MockTweetServiceMockRecorder) UpdateLargeImage(ctx, id, captureUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLargeImage", reflect.TypeOf((*MockTweetService)(nil).UpdateLargeImage), ctx, id, captureUrl)
}

// UpdateThumbImage mocks base method.
func (m *MockTweetService) UpdateThumbImage(ctx context.Context, id, captureUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThumbImage", ctx, id, captureUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThumbImage indicates an expected call of UpdateThumbImage.
func (mr *MockTweetServiceMockRecorder) UpdateThumbImage(ctx, id, captureUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThumbImage", reflect.TypeOf((*MockTweetService)(nil).UpdateThumbImage), ctx, id, captureUrl)
}

// MockSearchService is a mock of SearchService interface.
type MockSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceMockRecorder
	isgomock struct{}
}

// MockSearchServiceMockRecorder is the mock recorder for MockSearchService.
type MockSearchServiceMockRecorder struct {
	mock *MockSearchService
}

// NewMockSearchService creates a new mock instance.
func NewMockSearchService(ctrl *gomock.Controller) *MockSearchService {
	mock := &MockSearchService{ctrl: ctrl}
	mock.recorder = &MockSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchService) EXPECT() *MockSearchServiceMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockSearchService) Put(ctx context.Context, tweetId, fullText, author string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, tweetId, fullText, author)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockSearchServiceMockRecorder) Put(ctx, tweetId, fullText, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockSearchService)(nil).Put), ctx, tweetId, fullText, author)
}

// Search mocks base method.
func (m *MockSearchService) Search(ctx context.Context, term string, size int) ([]SearchModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, term, size)
	ret0, _ := ret[0].([]SearchModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchServiceMockRecorder) Search(ctx, term, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchService)(nil).Search), ctx, term, size)
}

// MockBrowserService is a mock of BrowserService interface.
type MockBrowserService struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserServiceMockRecorder
	isgomock struct{}
}

// MockBrowserServiceMockRecorder is the mock recorder for MockBrowserService.
type MockBrowserServiceMockRecorder struct {
	mock *MockBrowserService
}

// NewMockBrowserService creates a new mock instance.
func NewMockBrowserService(ctrl *gomock.Controller) *MockBrowserService {
	mock := &MockBrowserService{ctrl: ctrl}
	mock.recorder = &MockBrowserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowserService) EXPECT() *MockBrowserServiceMockRecorder {
	return m.recorder
}

// CaptureSaveUpdateDatabase mocks base method.
func (m *MockBrowserService) CaptureSaveUpdateDatabase(ctx context.Context, model *CaptureRequestModel) (*CaptureResponseModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaptureSaveUpdateDatabase", ctx, model)
	ret0, _ := ret[0].(*CaptureResponseModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CaptureSaveUpdateDatabase indicates an expected call of CaptureSaveUpdateDatabase.
func (mr *MockBrowserServiceMockRecorder) CaptureSaveUpdateDatabase(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureSaveUpdateDatabase", reflect.TypeOf((*MockBrowserService)(nil).CaptureSaveUpdateDatabase), ctx, model)
}

// CaptureURL mocks base method.
func (m *MockBrowserService) CaptureURL(ctx context.Context, model *CaptureRequestModel) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaptureURL", ctx, model)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CaptureURL indicates an expected call of CaptureURL.
func (mr *MockBrowserServiceMockRecorder) CaptureURL(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureURL", reflect.TypeOf((*MockBrowserService)(nil).CaptureURL), ctx, model)
}

// Close mocks base method.
func (m *MockBrowserService) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockBrowserServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrowserService)(nil).Close))
}

// SaveCapture mocks base method.
func (m *MockBrowserService) SaveCapture(ctx context.Context, originalImage []byte, model *CaptureRequestModel) (*CaptureResponseModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCapture", ctx, originalImage, model)
	ret0, _ := ret[0].(*CaptureResponseModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveCapture indicates an expected call of SaveCapture.
func (mr *MockBrowserServiceMockRecorder) SaveCapture(ctx, originalImage, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCapture", reflect.TypeOf((*MockBrowserService)(nil).SaveCapture), ctx, originalImage, model)
}

// MockContentService is a mock of ContentService interface.
type MockContentService struct {
	ctrl     *gomock.Controller
	recorder *MockContentServiceMockRecorder
	isgomock struct{}
}

// MockContentServiceMockRecorder is the mock recorder for MockContentService.
type MockContentServiceMockRecorder struct {
	mock *MockContentService
}

// NewMockContentService creates a new mock instance.
func NewMockContentService(ctrl *gomock.Controller) *MockContentService {
	mock := &MockContentService{ctrl: ctrl}
	mock.recorder = &MockContentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentService) EXPECT() *MockContentServiceMockRecorder {
	return m.recorder
}

// StoreContactRequest mocks base method.
func (m *MockContentService) StoreContactRequest(ctx context.Context, senderMail, senderName, message, captcha string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreContactRequest", ctx, senderMail, senderName, message, captcha)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreContactRequest indicates an expected call of StoreContactRequest.
func (mr *MockContentServiceMockRecorder) StoreContactRequest(ctx, senderMail, senderName, message, captcha any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreContactRequest", reflect.TypeOf((*MockContentService)(nil).StoreContactRequest), ctx, senderMail, senderName, message, captcha)
}
